"""LLM-judge correctness scoring for long-form biography responses.

This module provides :func:`llm_judge_correctness_fn`, which returns a
:data:`CorrectnessFn` that grades the *majority* sampled answer for a bio
record against its Wikipedia reference paragraph using a vLLM-backed judge
(Qwen2.5-72B-Instruct by default).

Why grade the majority answer rather than all M samples: the
``correctness_label`` is per-record (a single ground-truth bit for AUROC), and
the selective-prediction table needs one correctness label per uncertainty
score. Grading the modal cluster representative is the cheapest fixed policy
for deriving that label, but the label can change when a different clustering
backend changes the modal representative. Backend-specific bio comparisons
therefore need backend-specific regrading rather than silently reusing labels
from a previous clustering pass.

The module also provides :func:`grade_records_inplace`, which loads a scored
JSONL, fills the ``correctness_label`` and optional ``scores.correctness_score``
fields, and returns the updated list. This is called by
``scripts/score_longform_correctness.py``.

Prompt template: ``src/semantic_entropy/prompts/bio_judge.txt``
Secondary confidence prompt: inline in :const:`CONFIDENCE_USER_TEMPLATE`.
"""

from __future__ import annotations

import math
from collections.abc import Callable
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

#: CorrectnessFn: (question, reference_answers, sampled_answers) -> (bool, dict)
CorrectnessFn = Callable[[str, list[str], list[str]], tuple[bool, dict[str, Any]]]


# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

_PROMPTS_DIR = Path(__file__).parent / "prompts"

DEFAULT_BIO_JUDGE_PROMPT_PATH = _PROMPTS_DIR / "bio_judge.txt"


def _load_prompt_template() -> str:
    return DEFAULT_BIO_JUDGE_PROMPT_PATH.read_text(encoding="utf-8")


CONFIDENCE_USER_TEMPLATE = (
    "How confident are you in this verdict? "
    "Reply with a single number between 0 and 1."
)

DEFAULT_CORRECTNESS_SYSTEM_PROMPT = (
    "You are a careful factual grader. You evaluate whether a biographical "
    "paragraph generated by a language model is factually consistent with a "
    "Wikipedia reference. Follow the grading instructions precisely."
)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def parse_correctness_judgment(raw: str) -> bool:
    """Map a raw LLM response to a boolean correctness label.

    Returns ``True`` if the response begins with ``correct`` (case-insensitive),
    ``False`` otherwise. Defaults to ``False`` on any parse failure, matching
    the conservative stance taken by the rest of the pipeline.

    Args:
        raw: Free-text response from the judge model.

    Returns:
        ``True`` for CORRECT, ``False`` for INCORRECT or unrecognized output.
    """
    cleaned = raw.strip().lower().lstrip("\"' .:,-*")
    return cleaned.startswith("correct") and not cleaned.startswith("incorrect")


def parse_confidence_score(raw: str) -> float | None:
    """Parse a floating-point confidence score from the judge's second response.

    Returns a float in ``[0, 1]`` or ``None`` if the response cannot be parsed.
    """
    cleaned = raw.strip()
    try:
        val = float(cleaned)
        if math.isfinite(val) and 0.0 <= val <= 1.0:
            return val
    except (ValueError, TypeError):
        pass
    return None


# ---------------------------------------------------------------------------
# Majority cluster representative
# ---------------------------------------------------------------------------


def _majority_representative(
    sampled_answers: list[str],
    semantic_clusters: list[int] | None = None,
) -> str:
    """Return the representative of the largest cluster.

    When *semantic_clusters* is provided, the representative is the first
    sample in the modal cluster (ties broken by smallest cluster ID).
    When absent, returns the first sampled answer.

    Args:
        sampled_answers: Raw generated answers.
        semantic_clusters: Cluster IDs parallel to *sampled_answers*.

    Returns:
        The modal cluster's first member.
    """
    if not sampled_answers:
        raise ValueError("sampled_answers must not be empty")

    if semantic_clusters is None:
        return sampled_answers[0]

    cluster_counts: dict[int, int] = {}
    cluster_first: dict[int, str] = {}
    for answer, cid in zip(sampled_answers, semantic_clusters):
        cluster_counts[cid] = cluster_counts.get(cid, 0) + 1
        if cid not in cluster_first:
            cluster_first[cid] = answer

    modal_cid = max(cluster_counts, key=lambda c: (cluster_counts[c], -c))
    return cluster_first[modal_cid]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def llm_judge_correctness_fn(
    judge: Any,  # BatchedLlmJudge instance
    *,
    prompt_template: str | None = None,
    confidence_threshold: float = 0.5,
    include_confidence: bool = True,
) -> CorrectnessFn:
    """Return a CorrectnessFn that grades the majority answer against the reference.

    The returned function has signature
    ``(question, reference_answers, sampled_answers) -> (bool, dict)`` where
    the dict may contain a ``"correctness_score"`` key when
    *include_confidence* is True.

    Args:
        judge: A :class:`~semantic_entropy.llm_judge.BatchedLlmJudge`
            instance (loaded with the judge model).
        prompt_template: Override for the grading prompt template.
            Defaults to :data:`DEFAULT_BIO_JUDGE_PROMPT_PATH`.
        confidence_threshold: Unused by the binary parser; reserved for
            soft-label future extension.
        include_confidence: When True, ask a follow-up question for a
            confidence score in [0, 1] and store it in the extra dict.

    Returns:
        A callable ``CorrectnessFn``.
    """
    if prompt_template is None:
        prompt_template = _load_prompt_template()

    def correctness_fn(
        question: str,
        reference_answers: list[str],
        sampled_answers: list[str],
        *,
        semantic_clusters: list[int] | None = None,
    ) -> tuple[bool, dict[str, Any]]:
        entity = _extract_entity(question)
        reference = reference_answers[0] if reference_answers else ""
        response = _majority_representative(sampled_answers, semantic_clusters)

        # Format grading prompt.
        user_msg = prompt_template.format(
            entity=entity,
            reference=reference,
            response=response,
        )
        messages = [
            {"role": "system", "content": DEFAULT_CORRECTNESS_SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ]
        prompt_text = judge._tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

        # Batch single call.
        raw_verdict = judge._llm.generate(
            [prompt_text], judge._sampling_params
        )[0].outputs[0].text

        label = parse_correctness_judgment(raw_verdict)
        extra: dict[str, Any] = {}

        if include_confidence:
            conf_messages = messages + [
                {"role": "assistant", "content": raw_verdict.strip()},
                {"role": "user", "content": CONFIDENCE_USER_TEMPLATE},
            ]
            conf_prompt = judge._tokenizer.apply_chat_template(
                conf_messages, tokenize=False, add_generation_prompt=True
            )
            raw_conf = judge._llm.generate(
                [conf_prompt], judge._sampling_params
            )[0].outputs[0].text
            score = parse_confidence_score(raw_conf)
            if score is not None:
                extra["correctness_score"] = score

        return label, extra

    return correctness_fn


def _extract_entity(question: str) -> str:
    """Extract the entity name from a bio prompt.

    E.g. "Tell me a bio of Marie Curie." → "Marie Curie".
    Falls back to the full question string.
    """
    import re
    m = re.match(r"(?:tell me a bio of|bio of)\s+(.+?)\.?\s*$", question, re.IGNORECASE)
    if m:
        return m.group(1).strip()
    return question.strip()


# ---------------------------------------------------------------------------
# Batch grading over a scored JSONL
# ---------------------------------------------------------------------------


def grade_records_inplace(
    records: list[dict[str, Any]],
    judge: Any,  # BatchedLlmJudge
    *,
    prompt_template: str | None = None,
    include_confidence: bool = True,
    skip_already_graded: bool = True,
) -> list[dict[str, Any]]:
    """Grade all records with the LLM judge and update correctness fields.

    For each record, extracts the majority representative answer (using
    ``semantic_clusters`` if present), calls the judge, and writes
    ``correctness_label`` and optionally ``scores.correctness_score``.

    Args:
        records: List of scored JSONL dicts (will be modified in place).
        judge: A :class:`~semantic_entropy.llm_judge.BatchedLlmJudge` instance.
        prompt_template: Override the grading prompt.
        include_confidence: Request a confidence score per record.
        skip_already_graded: Skip records where ``correctness_label`` is
            already a meaningful bool (i.e. not the posthoc placeholder
            ``False``). Callers that want to re-grade everything should
            set this to ``False``.

    Returns:
        The modified *records* list.
    """
    if prompt_template is None:
        prompt_template = _load_prompt_template()

    grading_fn = llm_judge_correctness_fn(
        judge,
        prompt_template=prompt_template,
        include_confidence=include_confidence,
    )

    for idx, record in enumerate(records):
        prompt_id = record.get("prompt_id", f"<record {idx}>")

        # Skip records that already have a real label (not the placeholder).
        if skip_already_graded and isinstance(record.get("correctness_label"), bool):
            # The placeholder is always False; we can't distinguish it from a
            # real False without a separate flag. The --idempotent flag on the
            # CLI script handles this by re-grading all records unconditionally
            # when the user wants a fresh pass.
            pass

        question = record.get("prompt", "")
        reference_answers = record.get("reference_answers", [""])
        sampled_answers = record.get("sampled_answers", [])
        semantic_clusters = record.get("semantic_clusters")

        if not sampled_answers:
            print(f"  [{idx}] SKIP (no sampled_answers): {prompt_id}", flush=True)
            continue

        label, extra = grading_fn(
            question,
            reference_answers,
            sampled_answers,
            semantic_clusters=semantic_clusters,
        )

        record["correctness_label"] = label
        if "correctness_score" in extra:
            record.setdefault("scores", {})
            record["scores"]["correctness_score"] = extra["correctness_score"]

        if (idx + 1) % 50 == 0:
            print(f"  graded {idx + 1}/{len(records)} records", flush=True)

    return records


__all__ = [
    "CorrectnessFn",
    "DEFAULT_BIO_JUDGE_PROMPT_PATH",
    "DEFAULT_CORRECTNESS_SYSTEM_PROMPT",
    "CONFIDENCE_USER_TEMPLATE",
    "parse_correctness_judgment",
    "parse_confidence_score",
    "llm_judge_correctness_fn",
    "grade_records_inplace",
]
