"""LLM-judge correctness scoring for long-form biography responses.

The active grading path selects a clustering-independent response: a saved
most-likely answer when present, otherwise the most frequent exact normalized
surface form, breaking ties by first occurrence. It assigns one binary
reference-consistency verdict to that response, not a score to each claim.
The resulting labels can be reused across entailment backends on the same
samples. The lower-level grading callable retains a legacy majority-cluster
fallback only when no explicit representative is supplied.

The module also provides :func:`grade_records_inplace`, which loads a scored
JSONL, fills the ``correctness_label`` and optional ``scores.correctness_score``
fields, marks their provenance as an exploratory automated proxy, and returns
the updated list. This is called by
``scripts/score_longform_correctness.py``.

Prompt template: ``src/semantic_entropy/prompts/bio_judge.txt``
Secondary confidence prompt: inline in :const:`CONFIDENCE_USER_TEMPLATE`.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any

from semantic_entropy.label_provenance import (
    automated_label_provenance,
    validate_label_provenance,
)

# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

#: CorrectnessFn: (question, reference_answers, sampled_answers) -> (bool, dict)
CorrectnessFn = Callable[[str, list[str], list[str]], tuple[bool, dict[str, Any]]]


# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------

_PROMPTS_DIR = Path(__file__).parent / "prompts"

DEFAULT_BIO_JUDGE_PROMPT_PATH = _PROMPTS_DIR / "bio_judge.txt"


def _load_prompt_template() -> str:
    return DEFAULT_BIO_JUDGE_PROMPT_PATH.read_text(encoding="utf-8")


CONFIDENCE_USER_TEMPLATE = (
    "How confident are you in this verdict? "
    "Reply with a single number between 0 and 1."
)

DEFAULT_CORRECTNESS_SYSTEM_PROMPT = (
    "You are a careful factual grader. You evaluate whether a biographical "
    "paragraph generated by a language model is factually consistent with a "
    "Wikipedia reference. Follow the grading instructions precisely."
)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def parse_correctness_judgment(raw: str) -> bool:
    """Map a raw LLM response to a boolean correctness label.

    Accepts only responses beginning with ``correct`` or ``incorrect``
    (case-insensitive). Unrecognized or empty output raises instead of silently
    turning a judge failure into a factual-error label.

    Args:
        raw: Free-text response from the judge model.

    Returns:
        ``True`` for CORRECT and ``False`` for INCORRECT.

    Raises:
        ValueError: If the verdict is empty or unrecognized.
    """
    cleaned = raw.strip().lower().lstrip("\"' .:,-*")
    if cleaned.startswith("incorrect"):
        return False
    if cleaned.startswith("correct"):
        return True
    raise ValueError(f"unrecognized correctness judgment: {raw!r}")


def parse_confidence_score(raw: str) -> float | None:
    """Parse a floating-point confidence score from the judge's second response.

    Returns a float in ``[0, 1]`` or ``None`` if the response cannot be parsed.
    """
    cleaned = raw.strip()
    try:
        val = float(cleaned)
        if math.isfinite(val) and 0.0 <= val <= 1.0:
            return val
    except (ValueError, TypeError):
        pass
    return None


# ---------------------------------------------------------------------------
# Majority cluster representative
# ---------------------------------------------------------------------------


def _majority_representative(
    sampled_answers: list[str],
    semantic_clusters: list[int] | None = None,
) -> str:
    """Return the representative of the largest cluster.

    When *semantic_clusters* is provided, the representative is the first
    sample in the modal cluster (ties broken by smallest cluster ID).
    When absent, returns the first sampled answer.

    Args:
        sampled_answers: Raw generated answers.
        semantic_clusters: Cluster IDs parallel to *sampled_answers*.

    Returns:
        The modal cluster's first member.
    """
    if not sampled_answers:
        raise ValueError("sampled_answers must not be empty")

    if semantic_clusters is None:
        return sampled_answers[0]

    cluster_counts: dict[int, int] = {}
    cluster_first: dict[int, str] = {}
    for answer, cid in zip(sampled_answers, semantic_clusters):
        cluster_counts[cid] = cluster_counts.get(cid, 0) + 1
        if cid not in cluster_first:
            cluster_first[cid] = answer

    modal_cid = max(cluster_counts, key=lambda c: (cluster_counts[c], -c))
    return cluster_first[modal_cid]


def _fixed_representative(record: dict[str, Any]) -> str:
    """Return a clustering-INDEPENDENT answer to grade for correctness.

    The bio correctness proxy must be a property of the generation, not of the
    clustering backend used downstream. Grading the *majority-cluster*
    representative made the label depend on the backend (different clusters →
    different modal answer → different label), so the same record could be
    graded correct under one NLI model and incorrect under another.

    This grades a fixed representative instead, in priority order:
    1. ``most_likely_answer`` — the single low-temperature answer (paper
       protocol; present when generation used ``paper_accuracy``);
    2. the most frequent *exact* sampled answer (clustering-independent);
    3. the first sampled answer.
    None of these depends on ``semantic_clusters``, so the label is stable
    across every clustering backend.
    """
    mla = str(record.get("most_likely_answer") or "").strip()
    if mla:
        return mla
    sampled = [s for s in record.get("sampled_answers", []) if str(s).strip()]
    if not sampled:
        sampled = list(record.get("sampled_answers", []))
    if not sampled:
        return ""
    from collections import Counter

    return Counter(sampled).most_common(1)[0][0]


def _fixed_representative_policy(record: dict[str, Any]) -> str:
    if str(record.get("most_likely_answer") or "").strip():
        return "most_likely_answer"
    return "exact_surface_mode_first_tie"


def _record_question(record: dict[str, Any]) -> str:
    """Resolve the original question from either supported schema field."""

    question = str(record.get("question") or "").strip()
    prompt = str(record.get("prompt") or "").strip()
    if question and prompt and question != prompt:
        raise ValueError("record has conflicting question and prompt fields")
    resolved = question or prompt
    if not resolved:
        raise ValueError("record has no non-empty question or prompt field")
    return resolved


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def llm_judge_correctness_fn(
    judge: Any,  # BatchedLlmJudge instance
    *,
    prompt_template: str | None = None,
    confidence_threshold: float = 0.5,
    include_confidence: bool = True,
) -> CorrectnessFn:
    """Return a CorrectnessFn that grades the majority answer against the reference.

    The returned function has signature
    ``(question, reference_answers, sampled_answers) -> (bool, dict)`` where
    the dict may contain a ``"correctness_score"`` key when
    *include_confidence* is True.

    Args:
        judge: A :class:`~semantic_entropy.llm_judge.BatchedLlmJudge`
            instance (loaded with the judge model).
        prompt_template: Override for the grading prompt template.
            Defaults to :data:`DEFAULT_BIO_JUDGE_PROMPT_PATH`.
        confidence_threshold: Unused by the binary parser; reserved for
            soft-label future extension.
        include_confidence: When True, ask a follow-up question for a
            confidence score in [0, 1] and store it in the extra dict.

    Returns:
        A callable ``CorrectnessFn``.
    """
    if prompt_template is None:
        prompt_template = _load_prompt_template()

    def correctness_fn(
        question: str,
        reference_answers: list[str],
        sampled_answers: list[str],
        *,
        semantic_clusters: list[int] | None = None,
        representative: str | None = None,
    ) -> tuple[bool, dict[str, Any]]:
        entity = _extract_entity(question)
        reference = reference_answers[0] if reference_answers else ""
        # Grade a clustering-INDEPENDENT representative when supplied (the
        # caller passes the low-temperature most-likely answer); fall back to
        # the legacy majority-cluster representative only when not given.
        response = (
            representative
            if representative is not None
            else _majority_representative(sampled_answers, semantic_clusters)
        )

        # Format grading prompt.
        user_msg = prompt_template.format(
            entity=entity,
            reference=reference,
            response=response,
        )
        messages = [
            {"role": "system", "content": DEFAULT_CORRECTNESS_SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ]
        prompt_text = judge._tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

        # Batch single call.
        raw_verdict = judge._llm.generate(
            [prompt_text], judge._sampling_params
        )[0].outputs[0].text

        label = parse_correctness_judgment(raw_verdict)
        extra: dict[str, Any] = {}

        if include_confidence:
            conf_messages = messages + [
                {"role": "assistant", "content": raw_verdict.strip()},
                {"role": "user", "content": CONFIDENCE_USER_TEMPLATE},
            ]
            conf_prompt = judge._tokenizer.apply_chat_template(
                conf_messages, tokenize=False, add_generation_prompt=True
            )
            raw_conf = judge._llm.generate(
                [conf_prompt], judge._sampling_params
            )[0].outputs[0].text
            score = parse_confidence_score(raw_conf)
            if score is not None:
                extra["correctness_score"] = score

        return label, extra

    return correctness_fn


def _extract_entity(question: str) -> str:
    """Extract the entity name from a bio prompt.

    E.g. "Tell me a bio of Marie Curie." → "Marie Curie".
    Falls back to the full question string.
    """
    import re
    m = re.match(r"(?:tell me a bio of|bio of)\s+(.+?)\.?\s*$", question, re.IGNORECASE)
    if m:
        return m.group(1).strip()
    return question.strip()


# ---------------------------------------------------------------------------
# Batch grading over a scored JSONL
# ---------------------------------------------------------------------------


def grade_records_inplace(
    records: list[dict[str, Any]],
    judge: Any,  # BatchedLlmJudge
    *,
    prompt_template: str | None = None,
    include_confidence: bool = True,
    skip_already_graded: bool = True,
) -> list[dict[str, Any]]:
    """Grade all records with the LLM judge and update correctness fields.

    For each record, selects a clustering-independent representative with
    :func:`_fixed_representative`, calls the judge, and writes
    ``correctness_label`` and optionally ``scores.correctness_score``.

    Args:
        records: List of scored JSONL dicts (will be modified in place).
        judge: A :class:`~semantic_entropy.llm_judge.BatchedLlmJudge` instance.
        prompt_template: Override the grading prompt.
        include_confidence: Request a confidence score per record.
        skip_already_graded: Skip records where ``correctness_label`` is
            already a meaningful bool (i.e. not the posthoc placeholder
            ``False``). Callers that want to re-grade everything should
            set this to ``False``.

    Returns:
        The modified *records* list.
    """
    if prompt_template is None:
        prompt_template = _load_prompt_template()

    grading_fn = llm_judge_correctness_fn(
        judge,
        prompt_template=prompt_template,
        include_confidence=include_confidence,
    )

    for idx, record in enumerate(records):
        prompt_id = record.get("prompt_id", f"<record {idx}>")

        # A boolean with provenance is a real label; a bare False remains the
        # historical phase-1 placeholder. Never overwrite a provenance-bearing
        # label on the default path, especially a published human annotation.
        existing_provenance = record.get("correctness_label_provenance")
        if (
            skip_already_graded
            and isinstance(record.get("correctness_label"), bool)
            and existing_provenance is not None
        ):
            validate_label_provenance(existing_provenance)
            continue
        if not skip_already_graded and isinstance(existing_provenance, Mapping):
            validated = validate_label_provenance(existing_provenance)
            if validated["scope"] == "primary_human_annotation":
                raise ValueError(
                    "published human correctness labels are immutable in the "
                    "automated long-form grading path"
                )

        question = _record_question(record)
        reference_answers = record.get("reference_answers", [""])
        sampled_answers = record.get("sampled_answers", [])

        if not sampled_answers:
            print(f"  [{idx}] SKIP (no sampled_answers): {prompt_id}", flush=True)
            continue

        # Grade a clustering-INDEPENDENT representative so the correctness
        # label is stable across clustering backends (see _fixed_representative).
        representative = _fixed_representative(record)
        label, extra = grading_fn(
            question,
            reference_answers,
            sampled_answers,
            representative=representative,
        )

        record["correctness_label"] = label
        record["correctness_label_provenance"] = automated_label_provenance(
            judge_model=str(getattr(judge, "model_name", "")),
            target="selected_biography_response_against_reference",
            representative_policy=_fixed_representative_policy(record),
        )
        if "correctness_score" in extra:
            record.setdefault("scores", {})
            record["scores"]["correctness_score"] = extra["correctness_score"]

        if (idx + 1) % 50 == 0:
            print(f"  graded {idx + 1}/{len(records)} records", flush=True)

    return records


__all__ = [
    "CorrectnessFn",
    "DEFAULT_BIO_JUDGE_PROMPT_PATH",
    "DEFAULT_CORRECTNESS_SYSTEM_PROMPT",
    "CONFIDENCE_USER_TEMPLATE",
    "parse_correctness_judgment",
    "parse_confidence_score",
    "llm_judge_correctness_fn",
    "grade_records_inplace",
]
