#!/usr/bin/env python3
"""Generate appendix tables from the committed automated validation results."""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]


def table(caption, label, columns, header, rows):
    return '\n'.join([
        '% Generated by scripts/build_robustness_tables.py. Do not edit by hand.',
        '% Input: results/robustness/ recorded exports.',
        r'\begin{table}[htb]', r'\thisfloatsetup{capposition=above}',
        r'\centering\footnotesize', '\\caption{' + caption + '}',
        '\\label{' + label + '}', r'\begingroup\setlength{\tabcolsep}{3pt}',
        '\\begin{tabular}{@{}' + columns + '@{}}', r'\toprule',
        header + r' \\', r'\midrule', *[r + r' \\' for r in rows],
        r'\bottomrule', r'\end{tabular}', r'\endgroup', r'\end{table}', ''])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('output', type=Path, nargs='?', default=ROOT / 'thesis/includes')
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    data = ROOT / 'results/robustness'
    boot = pd.read_csv(data / 'bootstrap_sensitivity.csv')
    boot = boot[boot.grader == 'llm_qwen2.5-72b']
    rows = []
    for condition, name in [('chat_0shot', 'Sentence'), ('default_5shot', 'Short phrase')]:
        for backend, model in [('microsoft_deberta-v2-xlarge-mnli', 'xlarge'),
                               ('cross-encoder_nli-deberta-v3-large', 'v3-large'),
                               ('Qwen_Qwen2.5-72B-Instruct', 'Qwen-72B')]:
            group = boot[(boot.condition == condition) & (boot.backend == backend)]
            entries = []
            for scheme in ['linked_questions', 'crossed_questions']:
                r = group[group.scheme == scheme].iloc[0]
                entries.append(f'$[{r.lower:+.3f}, {r.upper:+.3f}]$')
            rows.append(f'{name} & {model} & ${r.point_delta:+.3f}$ & ' + ' & '.join(entries))
    (args.output / 't_robustness_bootstrap.tex').write_text(table(
        'Additional semantic-minus-surface AUROC checks under Qwen grading. '
        'Both schemes share question draws across generators and seeds. The crossed '
        r'scheme also varies dataset and generator multiplicities. Entries are 95\,\% '
        'percentile ranges from 2,000 draws, with only three levels of each factor.',
        'tab:robustness-bootstrap', 'llccc',
        r'Condition & Entailment & $\Delta$ & Fixed grid & Crossed factors', rows))
    samples = pd.read_csv(data / 'clustering_summary.csv')
    samples = samples[(samples.grader == 'llm_qwen2.5-72b') & (samples.experiment == 'samples')]
    rows = []
    for m in [2, 4, 6, 8, 10]:
        values = []
        for condition in ['chat_0shot', 'default_5shot']:
            for method in ['raw', 'normalized', 'surface']:
                r = samples[(samples.condition == condition) & (samples.method == method)
                            & (samples.samples == m)].iloc[0]
                values.append(f'{r.mean_auroc:.3f}')
        rows.append(str(m) + ' & ' + ' & '.join(values))
    (args.output / 't_robustness_samples.tex').write_text(table(
        'Sample-count sensitivity on 270 fixed records per condition, DeBERTa-v3-large, '
        'Qwen grading. Raw and normalized columns use DSE. Surface counts normalized strings. '
        'Values average nine cell AUROCs and, for $M<10$, 50 answer-subset replicates. '
        'All cells have both correctness classes. These are conditional subset results.',
        'tab:robustness-samples', 'crrrrrr',
        r'& \multicolumn{3}{c}{Sentence} & \multicolumn{3}{c}{Short phrase} \\' + '\n' +
        r'$M$ & Raw & Normalized & Surface & Raw & Normalized & Surface', rows))


if __name__ == '__main__':
    main()
