#!/usr/bin/env python3
"""Build the Results and appendix tables and figures from the measurement file.

Main source: data/measurements.csv (10,350 rows), with data/seed_variability.csv.
The paired bootstrap intervals are read from results/. Writes .tex fragments
and figures, and prints an audit trail.

Usage: python scripts/build_thesis_tables.py data/measurements.csv thesis/includes

Intervals: the `units` scheme of scripts/paired_bootstrap_hierarchical.py --
resample the 9 (dataset, model) units with replacement, statistic = mean over
units of the mean-over-seeds value. Computable from cell-level AUROCs alone.
Record-level and hierarchical intervals require the cluster trees and come from
paired_bootstrap_hierarchical.py; those are quoted, not recomputed.
"""
import sys, os
import numpy as np
import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, 'data', 'measurements.csv')
OUT  = sys.argv[2] if len(sys.argv) > 2 else os.path.join(REPO, 'thesis', 'includes')
os.makedirs(OUT, exist_ok=True)
DDIR = os.path.dirname(os.path.abspath(DATA))
aux = lambda n: os.path.join(DDIR, n)


def res(n):
    """Locate a file in results/."""
    path = os.path.join(REPO, 'results', n)
    if not os.path.exists(path):
        raise SystemExit(f'missing required input: {path}')
    return path

XL = 'microsoft_deberta-v2-xlarge-mnli'
LG = 'cross-encoder_nli-deberta-v3-large'
QW = 'Qwen_Qwen2.5-72B-Instruct'
QJ, LJ, F1 = 'llm_qwen2.5-72b', 'llm_llama-3.1-70b', 'squad_token_f1'

PRETTY = {
    'semantic_entropy_full':      'Semantic entropy, likelihood-weighted',
    'discrete_semantic_entropy':  'Discrete semantic entropy',
    'surface_entropy':            'Surface entropy',
    'naive_entropy':              'Naive predictive entropy',
    'naive_sample_entropy':       'Naive sample entropy',
    'ptrue_uncertainty':          'P(True)',
    'accuracy_probe_uncertainty': 'Accuracy probe',
    'probe_uncertainty':          'Semantic entropy probe',
}
SHORT = {
    'microsoft_deberta-v2-xlarge-mnli': r'\texttt{xlarge}',
    'cross-encoder_nli-deberta-v3-large': r'\texttt{v3-large}',
    'Qwen_Qwen2.5-72B-Instruct': r'\texttt{Qwen-72B}',
}
BACKEND = {
    XL: r'\texttt{deberta-v2-xlarge-mnli}',
    LG: r'\texttt{nli-deberta-v3-large}',
    QW: r'\texttt{Qwen2.5-72B-Instruct}',
    'exact-match': r'\texttt{exact-match}',
    'posthoc-nli-deberta-v3-base':  r'\texttt{nli-deberta-v3-base}',
    'posthoc-nli-deberta-v3-large': r'\texttt{nli-deberta-v3-large}',
    'posthoc-llm-judge-qwen2.5-72b-instruct': r'\texttt{Qwen2.5-72B-Instruct}',
}
GRADER = {QJ: 'Qwen judge', LJ: 'Llama judge', F1: 'token-F1'}
COND = {'chat_0shot': r'\texttt{chat\_0shot}', 'default_0shot': r'\texttt{default\_0shot}',
        'chat_5shot': r'\texttt{chat\_5shot}', 'default_5shot': r'\texttt{default\_5shot}'}

d = pd.read_csv(DATA)
sa = d[d.arm == 'short_answer']
lf = d[d.arm == 'long_form']
T1 = sa[sa.temperature == 1.0]
BOOT = pd.read_csv(res('paired_bootstrap_se_vs_surface.csv'))
LONGFORM_BOOT = pd.read_csv(res('paired_bootstrap_longform.csv'))
SEED_VARIABILITY = pd.read_csv(aux('seed_variability.csv'))
SEED_REFERENCE = float(SEED_VARIABILITY.loc[
    SEED_VARIABILITY.method == 'discrete_semantic_entropy', 'mean_seed_range'].mean())
RNG = np.random.default_rng(20260831)
NBOOT = 2000
AUDIT = []


def cells(df, value='auroc'):
    """(dataset, model, seed) -> value, for one method in one slice."""
    return df.set_index(['dataset', 'model', 'seed'])[value]


def unit_stat(s):
    """Mean over the 9 units of the mean over seeds. s indexed by (ds,model,seed)."""
    return s.groupby(level=[0, 1]).mean().mean()


def unit_ci(s, nboot=NBOOT):
    """Percentile CI resampling the 9 (dataset, model) units with replacement."""
    per_unit = s.groupby(level=[0, 1]).mean()
    v = per_unit.to_numpy(float)
    n = v.size
    if n == 0:
        return np.nan, np.nan, np.nan
    draws = v[RNG.integers(0, n, size=(nboot, n))].mean(axis=1)
    lo, hi = np.percentile(draws, [2.5, 97.5])
    return float(v.mean()), float(lo), float(hi)


def paired(df, m1, m2, value='auroc'):
    """Paired per-cell difference m1 - m2 within one slice."""
    p = df.pivot_table(index=['dataset', 'model', 'seed'], columns='method', values=value)
    if m1 not in p or m2 not in p:
        return pd.Series(dtype=float)
    return (p[m1] - p[m2]).dropna()


def fmt(x, n=3):
    return '---' if pd.isna(x) else f'{x:.{n}f}'


def fmtpm(x, n=3):
    return '---' if pd.isna(x) else f'{x:+.{n}f}'


# Every generated table carries this line so a number is never more than one
# hop from the script that produced it. scripts/check_table_provenance.py
# asserts it is present, and the thesis never renders it because it is a
# LaTeX comment.
PROVENANCE = ('% Generated by scripts/build_thesis_tables.py. Do not edit by hand.\n'
              '% Inputs: measurement package and supporting exports; see the builder for each table.\n')


def write(name, body):
    path = os.path.join(OUT, name)
    if name.endswith('.tex'):
        body = PROVENANCE + body
    open(path, 'w', encoding='utf-8').write(body)
    print(f'  wrote {path}')


def table(caption, label, colspec, header, rows, note=None, small=True):
    out = ['\\begin{table}[htb]', '\\thisfloatsetup{capposition=above}', '\\centering']
    if small:
        out.append('\\footnotesize')
    out += [f'\\caption{{{caption}}}', f'\\label{{{label}}}',
            '\\begingroup', '\\setlength{\\tabcolsep}{3pt}',
            f'\\begin{{tabular}}{{{colspec}}}', '\\toprule', header, '\\midrule']
    out += rows
    out += ['\\bottomrule', '\\end{tabular}', '\\endgroup']
    if note:
        out.append(f'\\par\\vspace{{2pt}}\\footnotesize {note}')
    out.append('\\end{table}')
    return '\n'.join(out) + '\n'


# ---------------------------------------------------------------- 5.1 sentence-length
def t_sentence_length():
    sl = T1[(T1.condition == 'chat_0shot') & (T1.grader == QJ)]
    order = ['semantic_entropy_full', 'discrete_semantic_entropy', 'surface_entropy',
             'accuracy_probe_uncertainty', 'ptrue_uncertainty', 'naive_entropy',
             'naive_sample_entropy', 'probe_uncertainty']
    rows = []
    for m in order:
        # each estimator on the backend it was collected under
        b = {'ptrue_uncertainty': XL, 'probe_uncertainty': LG,
             'accuracy_probe_uncertainty': LG}.get(m, XL)
        s = cells(sl[(sl.method == m) & (sl.entailment_backend == b)])
        mu, lo, hi = unit_ci(s)
        nm = PRETTY[m]
        # The unit count is the same for every row, so the caption states it and
        # this check keeps that claim true instead of a constant column.
        units = len(s) // 3
        if units != 9:
            raise SystemExit(
                f'tab:sentence-length: {m} covers {units} units, caption says nine')
        rows.append(f'{nm} & {fmt(mu)} & [{fmt(lo)}, {fmt(hi)}] \\\\')
        AUDIT.append(('5.1 sentence-length', m, b, round(mu, 4)))
    return table(
        'Sentence-length answers (\\texttt{chat\\_0shot}), Qwen judge, $T=1.0$. AUROC '
        'against answer incorrectness, averaged over nine dataset--model combinations. '
        'These combinations are the statistical units resampled for the intervals. '
        'Methods that need entailment clusters use the released-code default '
        '\\texttt{deberta-v2-xlarge-mnli}. Both probes use '
        '\\texttt{nli-deberta-v3-large}.',
        'tab:sentence-length', '@{}lcc@{}',
        'Method & AUROC & 95\\,\\% CI \\\\', rows)


# ---------------------------------------------------------------- 5.2 short-phrase
def t_short_phrase():
    rows = []
    for g in [F1, QJ, LJ]:
        sub = T1[(T1.condition == 'default_5shot') & (T1.grader == g) &
                 (T1.entailment_backend == XL)]
        vals = {}
        for m in ['discrete_semantic_entropy', 'surface_entropy', 'naive_entropy']:
            vals[m] = unit_stat(cells(sub[sub.method == m]))
        gap = paired(sub, 'discrete_semantic_entropy', 'surface_entropy')
        mu, lo, hi = unit_ci(gap)
        rows.append(f'{GRADER[g]} & {fmt(vals["discrete_semantic_entropy"],4)} & '
                    f'{fmt(vals["surface_entropy"],4)} & {fmt(vals["naive_entropy"],4)} & '
                    f'{fmtpm(mu,4)} & [{fmtpm(lo,3)}, {fmtpm(hi,3)}] \\\\')
        AUDIT.append(('5.2 short-phrase', g, 'gap', round(mu, 4)))
    return table(
        'Short-phrase answers (\\texttt{default\\_5shot}), released-code entailment '
        'model, $T=1.0$, under all three correctness rules. The final two columns give '
        'the paired AUROC difference (discrete semantic entropy minus surface entropy) '
        'and its interval, which resamples the nine statistical units.',
        'tab:short-phrase', '@{}lccccc@{}',
        r'Correctness rule & Discrete SE & Surface & Naive pred. & \makecell{AUROC\\difference} & \makecell{95\,\% CI\\(units)} \\',
        rows)


# ---------------------------------------------------------------- 5.3 SE vs surface
def t_canonical_eight():
    rows = []
    for cond in ['chat_0shot', 'default_0shot', 'chat_5shot', 'default_5shot']:
        for g in [QJ, LJ]:
            r = BOOT[(BOOT.condition == cond) & (BOOT.entailment_backend == XL) &
                     (BOOT.grader == g)]
            if r.empty:
                continue
            r = r.iloc[0]
            rows.append(f'{COND[cond]} & {GRADER[g]} & {fmtpm(r.delta,4)} & '
                        f'[{fmtpm(r.hier_lo,3)}, {fmtpm(r.hier_hi,3)}] \\\\')
            AUDIT.append(('5.3 canonical8', f'{cond}|{g}', 'delta/hier',
                          [round(float(r.delta), 4), round(float(r.hier_lo), 4),
                           round(float(r.hier_hi), 4)]))
    return table(
        'Discrete semantic entropy against surface entropy on the entailment model the '
        'released code loads, under LLM grading: four prompting conditions crossed with '
        'two different LLM judges. AUROC differences and 95\\,\\% intervals come from the '
        'hierarchical '
        'paired bootstrap, which resamples both the nine (dataset, model) units and the '
        'records within them. Not one of the eight intervals excludes zero.',
        'tab:canonical-eight', '@{}llcc@{}',
        r'Condition & Judge & \makecell{AUROC\\difference} & \makecell{95\,\% CI\\(hierarchical)} \\',
        rows)


def t_resampling_schemes():
    rows = []
    desc = {'records': 'records, units fixed', 'units': 'the 9 units', 'hier': 'both'}
    for sch in ['records', 'units', 'hier']:
        lo, hi = BOOT[f'{sch}_lo'], BOOT[f'{sch}_hi']
        se, sf = int((lo > 0).sum()), int((hi < 0).sum())
        w = float((hi - lo).mean())
        nm = f'\\texttt{{{sch}}}'
        if sch == 'hier':
            rows.append(f'\\textbf{{{nm}}} & \\textbf{{{desc[sch]}}} & '
                        f'\\textbf{{{se+sf} / {len(BOOT)}}} & \\textbf{{{se}}} & '
                        f'\\textbf{{{sf}}} & \\textbf{{{w:.4f}}} \\\\')
        else:
            rows.append(f'{nm} & {desc[sch]} & {se+sf} / {len(BOOT)} & {se} & {sf} & '
                        f'{w:.4f} \\\\')
        AUDIT.append(('5.3 schemes', sch, 'resolved/SE/surface/width',
                      [se + sf, se, sf, round(w, 4)]))
    return table(
        'The same 24 comparisons under three resampling schemes. When only records are '
        'resampled, 18 of 24 confidence intervals exclude zero and the intervals are '
        'roughly three times narrower. Resampling the statistical units as well leaves '
        '11 intervals that exclude zero and changes which method is favored most often.',
        'tab:resampling-schemes', '@{}llcccc@{}',
        r'& & & \multicolumn{2}{c}{Favored method} & \\'
        '\n\\cmidrule(lr){4-5}\n'
        r'Scheme & What it varies & \makecell{CIs excluding\\zero} & SE & Surface & \makecell{Mean CI\\width} \\',
        rows)


def t_all_slices():
    rows = []
    for cond in ['chat_0shot', 'default_0shot', 'chat_5shot', 'default_5shot']:
        for b in [XL, LG, QW]:
            for g in [QJ, LJ, F1]:
                r = BOOT[(BOOT.condition == cond) & (BOOT.entailment_backend == b) &
                         (BOOT.grader == g)]
                if r.empty:
                    continue
                r = r.iloc[0]
                res = ('SE' if r.hier_lo > 0 else
                       ('surface' if r.hier_hi < 0 else 'neither'))
                rows.append(f'{COND[cond]} & {SHORT[b]} & {GRADER[g]} & '
                            f'{fmtpm(r.delta,4)} & '
                            f'[{fmtpm(r.hier_lo,3)}, {fmtpm(r.hier_hi,3)}] & {res} \\\\')
                AUDIT.append(('5.3 all slices', f'{cond}|{b}|{g}', 'delta',
                              round(float(r.delta), 4)))
    return table(
        'All 24 comparisons: discrete semantic entropy minus surface entropy, with '
        'hierarchical intervals resampling both the nine units and the records '
        'within them. The final column names the direction where the interval '
        "excludes zero. ``neither'' means the interval includes zero, not missing data "
        'or evidence of equivalence. Every comparison favoring semantic entropy uses the Qwen '
        'entailment model, and every comparison favoring surface entropy uses token-F1 '
        'grading.',
        'tab:all-slices', '@{}lllccl@{}',
        r'Condition & \makecell{Entailment\\model} & Grader & \makecell{AUROC\\difference} & \makecell{95\,\% CI\\(hierarchical)} & \makecell{Supported\\direction} \\',
        rows)


def t_ladder():
    """Compare four consecutive method changes, one change at a time."""
    import itertools
    rungs = [('naive_sample_entropy', 'naive_entropy',
              'count strings instead of reading likelihoods'),
             ('surface_entropy', 'naive_sample_entropy',
              'normalize the strings before counting'),
             ('discrete_semantic_entropy', 'surface_entropy',
              'cluster by meaning instead of by string'),
             ('semantic_entropy_full', 'discrete_semantic_entropy',
              'weight the clusters by likelihood')]
    rows = []
    for hi, lo, desc in rungs:
        mus, res_for, res_against = [], 0, 0
        for (c, b, g), sub in T1.groupby(['condition', 'entailment_backend', 'grader']):
            diff = paired(sub, hi, lo)
            if len(diff) < 9:
                continue
            mu, l, h = unit_ci(diff)
            mus.append(mu)
            res_for += int(l > 0)
            res_against += int(h < 0)
        mus = np.array(mus)
        pos = int((mus > 0).sum())
        star = r'\textbf{' if desc.startswith('normalize') else ''
        end = '}' if star else ''
        rows.append(f'{star}{desc}{end} & {star}{fmtpm(mus.mean(),4)}{end} & '
                    f'{star}{pos} / {len(mus)}{end} & {star}{res_for}{end} & '
                    f'{star}{res_against}{end} \\\\')
        AUDIT.append(('5.x ladder', desc, 'mean/pos/for/against',
                      [round(float(mus.mean()), 4), pos, res_for, res_against]))
    return table(
        'Four comparisons between consecutive methods. The semantic-versus-surface '
        'comparison also changes whether answers are normalized before grouping. '
        'The counts cover 24 configuration entries at $T=1.0$. String-only contrasts '
        'repeat 12 distinct condition--grader comparisons: the original conditions '
        'occur three times each, and the added conditions once each. Intervals '
        'resample the nine statistical units. Only '
        'answer normalization improves the mean AUROC in every comparison, and it is the '
        'only change whose mean difference exceeds the mean range across generation seeds.',
        'tab:ladder', '@{}p{4.8cm}cccc@{}',
        r'Change & \makecell{Mean AUROC\\difference} & \makecell{Positive\\comparisons} & \multicolumn{2}{c}{95\,\% CI} \\'
        '\n\\cmidrule(lr){4-5}\n'
        r' & & & \makecell{above\\zero} & \makecell{below\\zero} \\', rows)


# ---------------------------------------------------------------- 5.4 paper baselines
def t_paper_baselines():
    rows = []
    for comp, b in [('ptrue_uncertainty', XL), ('probe_uncertainty', LG),
                    ('accuracy_probe_uncertainty', LG)]:
        margins = []
        for cond in ['chat_0shot', 'default_5shot']:
            for g in [QJ, LJ, F1]:
                sub = T1[(T1.condition == cond) & (T1.entailment_backend == b) &
                         (T1.grader == g)]
                diff = paired(sub, 'discrete_semantic_entropy', comp)
                if not diff.empty:
                    margins.append(unit_stat(diff))
        if margins:
            rows.append(f'{PRETTY[comp]} & {len(margins)} & {fmtpm(np.mean(margins))} & '
                        f'[{fmtpm(min(margins))}, {fmtpm(max(margins))}] \\\\')
            AUDIT.append(('5.4 paper baselines', comp, 'mean margin',
                          round(float(np.mean(margins)), 4)))
    return table(
        r'Discrete semantic entropy against the baselines of Farquhar et al.~\cite{semantic_entropy_nature_2024} '
        r'and the semantic entropy probe of Kossen et al.~\cite{kossen_semantic_entropy_probes_2024}, '
        'over the comparisons in which each comparator was collected. Semantic entropy leads '
        'in every one.',
        'tab:paper-baselines', '@{}lccc@{}',
        r'Comparator & Comparisons & \makecell{Mean AUROC\\difference} & \makecell{Range across\\comparisons} \\', rows)


def t_ptrue_size():
    rows = []
    for cond in ['chat_0shot', 'default_5shot']:
        vals = []
        for mdl in ['meta-llama_Llama-3.1-70B-Instruct', 'meta-llama_Llama-3.1-8B-Instruct',
                    'mistralai_Mistral-7B-Instruct-v0.3']:
            sub = T1[(T1.condition == cond) & (T1.entailment_backend == XL) &
                     (T1.grader.isin([QJ, LJ])) &
                     (T1.method == 'ptrue_uncertainty') & (T1.model == mdl)]
            vals.append(sub.auroc.mean())
        rows.append(f'{COND[cond]} & ' + ' & '.join(fmt(v) for v in vals) + r' \\')
        AUDIT.append(('5.4 ptrue size', cond, 'auroc by model',
                      [round(float(v), 4) for v in vals]))
    return table(
        'P(True) by generator size, mean of the two LLM judges. Within the Llama family here the '
        'ordering is flat or inverted.',
        'tab:ptrue-size', '@{}lccc@{}',
        'Condition & Llama-3.1-70B & Llama-3.1-8B & Mistral-7B \\\\', rows)


# ---------------------------------------------------------------- 5.5 backend
def t_backend():
    rows = []
    for b in [XL, LG, QW]:
        sub = T1[(T1.condition == 'chat_0shot') & (T1.entailment_backend == b) &
                 (T1.grader == QJ)]
        dse = unit_stat(cells(sub[sub.method == 'discrete_semantic_entropy']))
        srf = unit_stat(cells(sub[sub.method == 'surface_entropy']))
        gap = paired(sub, 'discrete_semantic_entropy', 'surface_entropy')
        mu, lo, hi = unit_ci(gap)
        nm = (r'\makecell[l]{' + BACKEND[b] + r'\\\textbf{released-code default}}'
              if b == XL else BACKEND[b])
        rows.append(f'{nm} & {fmt(dse,4)} & {fmt(srf,4)} & {fmtpm(mu,4)} & '
                    f'[{fmtpm(lo,3)}, {fmtpm(hi,3)}] \\\\')
        AUDIT.append(('5.5 backend', b, 'dse', round(dse, 4)))
    return table(
        'Changing the entailment model while keeping the generated answers fixed '
        '(\\texttt{chat\\_0shot}, Qwen judge, $T=1.0$). Surface entropy is invariant to '
        'four decimal places across all three, as it must be: it never consults an '
        'entailment model.',
        'tab:backend', '@{}lcccc@{}',
        r'Entailment model & Discrete SE & Surface & \makecell{AUROC\\difference} & \makecell{95\,\% CI\\(units)} \\', rows)


def t_backend_grader_check():
    rows = []
    for b in [XL, LG, QW]:
        cells_ = []
        for g in [QJ, LJ]:
            sub = T1[(T1.condition == 'chat_0shot') & (T1.entailment_backend == b) &
                     (T1.grader == g)]
            cells_.append(unit_stat(paired(sub, 'discrete_semantic_entropy',
                                           'surface_entropy')))
        rows.append(f'{BACKEND[b]} & {fmtpm(cells_[0],4)} & {fmtpm(cells_[1],4)} \\\\')
        AUDIT.append(('5.5 grader check', b, 'qwen/llama',
                      [round(float(c), 4) for c in cells_]))
    return table(
        'The independent-grader check. The Qwen configuration uses one model as both '
        'entailment model and correctness judge. Re-grading the identical answers with '
        'Llama-3.1-70B gives the same ranking and very similar differences. The effect of '
        'changing the entailment model is therefore not caused only by one model filling '
        'both roles.',
        'tab:grader-check', '@{}lcc@{}',
        r'Entailment model & \makecell{AUROC difference\\Qwen judge} & \makecell{AUROC difference\\Llama judge} \\', rows)


def t_backend_by_model():
    rows = []
    order = ['meta-llama_Llama-3.1-8B-Instruct', 'mistralai_Mistral-7B-Instruct-v0.3',
             'meta-llama_Llama-3.1-70B-Instruct']
    nice = {'meta-llama_Llama-3.1-8B-Instruct': 'Llama-3.1-8B',
            'mistralai_Mistral-7B-Instruct-v0.3': 'Mistral-7B',
            'meta-llama_Llama-3.1-70B-Instruct': 'Llama-3.1-70B'}
    for mdl in order:
        vals = []
        for b in [XL, LG, QW]:
            sub = T1[(T1.condition == 'chat_0shot') & (T1.entailment_backend == b) &
                     (T1.grader == LJ) & (T1.model == mdl)]
            p_ = sub.pivot_table(index=['dataset', 'seed'], columns='method',
                                 values='auroc')
            vals.append((p_['discrete_semantic_entropy'] - p_['surface_entropy']).mean())
        ch = T1[(T1.condition == 'chat_0shot') & (T1.model == mdl) &
                (T1.entailment_backend == XL) &
                (T1.method == 'discrete_semantic_entropy')].mean_answer_chars.mean()
        rows.append(f'{nice[mdl]} & {ch:.0f} & ' + ' & '.join(fmtpm(v,3) for v in vals) + r' \\')
        AUDIT.append(('5.5 backend x model', nice[mdl], 'xlarge/v3-large/qwen',
                      [round(float(v), 4) for v in vals]))
    return table(
        'The discrete-semantic-entropy minus surface-entropy AUROC difference for each '
        'generator in \\texttt{chat\\_0shot} under the Llama judge, using the '
        'three entailment models. On the default cross-encoder the longest-answer generator gains '
        'least. On the 72B model the same generator gains most. The ordering '
        'inverts with the entailment model on identical generations.',
        'tab:backend-by-model', '@{}lrccc@{}',
        r'Generator & Mean chars & \texttt{xlarge} & \texttt{v3-large} & \texttt{Qwen-72B} \\', rows)


# ---------------------------------------------------------------- 5.6 the 2x2
def t_factorial():
    rows = []
    chars = {'chat_0shot': 255.2, 'default_0shot': 69.8, 'chat_5shot': 11.4,
             'default_5shot': 11.2}
    demos = {'chat_0shot': 0, 'default_0shot': 0, 'chat_5shot': 5, 'default_5shot': 5}
    for cond in ['chat_0shot', 'default_0shot', 'chat_5shot', 'default_5shot']:
        ms = []
        for g in [QJ, LJ]:
            sub = T1[(T1.condition == cond) & (T1.entailment_backend == XL) &
                     (T1.grader == g)]
            ms.append(unit_stat(paired(sub, 'discrete_semantic_entropy', 'surface_entropy')))
        mu = float(np.mean(ms))
        both = pd.concat([paired(T1[(T1.condition == cond) &
                                    (T1.entailment_backend == XL) & (T1.grader == g)],
                                 'discrete_semantic_entropy', 'surface_entropy')
                          for g in [QJ, LJ]])
        _, lo, hi = unit_ci(both)
        rows.append(f'{COND[cond]} & {chars[cond]:.1f} & {demos[cond]} & {fmtpm(mu)} & '
                    f'[{fmtpm(lo,3)}, {fmtpm(hi,3)}] \\\\')
        AUDIT.append(('5.6 factorial', cond, 'mean of two judges', round(mu, 4)))
    return table(
        'Secondary prompting analysis using the released-code entailment model, averaged '
        'over the two LLM judges. The clearest instruction comparison is between the two '
        'zero-shot conditions: both have no examples, so only the instruction changes. '
        'Every interval includes zero.',
        'tab:factorial', '@{}lccrc@{}',
        'Condition & Mean characters & Examples & AUROC difference & 95\\,\\% CI (units) \\\\', rows)


# ---------------------------------------------------------------- 5.7 long-form
LONGFORM_BACKEND = {
    'exact-match': 'Exact match',
    'posthoc-nli-deberta-v3-base': r'\makecell[l]{DeBERTa\\v3-base}',
    'posthoc-nli-deberta-v3-large': r'\makecell[l]{DeBERTa\\v3-large}',
    'posthoc-llm-judge-qwen2.5-72b-instruct': 'Qwen-72B',
}
LONGFORM_HEADER = (r'Entailment & \makecell{Discrete\\SE} & Surface & '
                   r'\makecell{Naive\\sample} & \makecell{$\Delta$ surface\\95\,\% CI} & '
                   r'\makecell{$\Delta$ naive sample\\95\,\% CI} \\')


def longform_intervals(model, backend):
    values = []
    for right in ['surface_entropy', 'naive_sample_entropy']:
        selected = LONGFORM_BOOT[(LONGFORM_BOOT.model == model) &
                                 (LONGFORM_BOOT.entailment_backend == backend) &
                                 (LONGFORM_BOOT.right == right)]
        if len(selected) != 1 or selected.iloc[0].scheme != 'records-only':
            raise ValueError(f'missing or invalid records-only interval: {model}, {backend}, {right}')
        r = selected.iloc[0]
        values.append(r'\makecell{' + fmtpm(r.delta, 3) + r'\\{[' +
                      fmtpm(r.records_lo, 3) + ', ' + fmtpm(r.records_hi, 3) + ']}}')
        AUDIT.append(('5.4 long-form records-only', f'{model}|{backend}|{right}',
                      'delta/lo/hi/p/n_records',
                      (r.delta, r.records_lo, r.records_hi, r.records_p, int(r.n_records))))
    return ' & '.join(values)


def t_longform():
    rows = []
    for b in ['exact-match', 'posthoc-nli-deberta-v3-base', 'posthoc-nli-deberta-v3-large',
              'posthoc-llm-judge-qwen2.5-72b-instruct']:
        sub = lf[lf.entailment_backend == b]
        v = {m: sub[sub.method == m].auroc.mean()
             for m in ['discrete_semantic_entropy', 'surface_entropy',
                       'naive_sample_entropy']}
        nm = LONGFORM_BACKEND[b]
        if b == 'posthoc-llm-judge-qwen2.5-72b-instruct':
            nm = r'\textbf{' + nm + '}'
        rows.append(f'{nm} & {fmt(v["discrete_semantic_entropy"],4)} & '
                    f'{fmt(v["surface_entropy"],4)} & {fmt(v["naive_sample_entropy"],4)} & '
                    + longform_intervals('all', b) + r' \\')
        AUDIT.append(('5.7 long-form', b, 'dse',
                      round(float(v['discrete_semantic_entropy']), 4)))
    acc = lf.accuracy.mean()
    note = (f'\\raggedright Mean paragraph acceptance rate: {acc:.3f} over the nine model--seed runs. '
            'The released-code default '
            '\\texttt{deberta-v2-xlarge-mnli} was not '
            'applied in this evaluation.\\par')
    return table(
        'Separate long-form evaluation: nine model--seed runs, 500 '
        'biographies each, and one binary reference-consistency verdict from the '
        'Qwen judge. The grouping protocol is specified in Appendix~\\ref{app:longform-details}. '
        'Each uncertainty score uses ten whole paragraphs. The final columns give discrete SE '
        'minus each string baseline and records-only 95\\,\\% intervals from '
        '2,000 paired resamples within runs. Generators and seeds stay fixed. '
        'These intervals exclude variation between dataset--generator units.',
        'tab:longform', '@{}lccccc@{}', LONGFORM_HEADER, rows, note=note)


# ---------------------------------------------------------------- 5.8 temperature
def t_temperature():
    rows = []
    for m in ['discrete_semantic_entropy', 'surface_entropy', 'naive_entropy']:
        vals = []
        for t in [0.1, 0.3, 0.5, 0.7, 1.0]:
            sub = sa[(sa.condition == 'chat_0shot') & (sa.entailment_backend == XL) &
                     (sa.grader == QJ) & (sa.temperature == t) & (sa.method == m)]
            vals.append(unit_stat(cells(sub)) if len(sub) else np.nan)
        best = int(np.nanargmax(vals))
        cellsf = [(r'\textbf{' + fmt(v) + '}') if i == best else fmt(v)
                  for i, v in enumerate(vals)]
        rows.append(f'{PRETTY[m]} & ' + ' & '.join(cellsf) + r' \\')
        AUDIT.append(('5.8 temperature', m, 'T=0.1..1.0',
                      [None if pd.isna(v) else round(float(v), 4) for v in vals]))
    return table(
        'Sampling temperature, sentence-length answers, released-code entailment model, '
        'and Qwen judge. Correctness labels from the main run are matched by '
        '\\texttt{prompt\\_id} and reused at all five temperatures. Thus this comparison '
        'changes the uncertainty score while holding the labels fixed. The sweep is '
        'reported only under LLM grading, for the reason given in '
        'Section~\\ref{sec:temperature-sweep}.',
        'tab:temperature', '@{}lccccc@{}',
        'Method & $T=0.1$ & $0.3$ & $0.5$ & $0.7$ & $1.0$ \\\\', rows)


# ---------------------------------------------------------------- 5.9 correctness rule
def t_correctness():
    rows = []
    for cond in ['chat_0shot', 'default_0shot', 'chat_5shot', 'default_5shot']:
        cellsf = []
        for g in [F1, QJ, LJ]:
            sub = T1[(T1.condition == cond) & (T1.entailment_backend == XL) &
                     (T1.grader == g) & (T1.method == 'discrete_semantic_entropy')]
            cellsf.append(sub.accuracy.mean())
        gaps = []
        for g in [F1, QJ, LJ]:
            sub = T1[(T1.condition == cond) & (T1.entailment_backend == XL) &
                     (T1.grader == g)]
            gaps.append(unit_stat(paired(sub, 'discrete_semantic_entropy',
                                         'surface_entropy')))
        rows.append(f'{COND[cond]} & ' + ' & '.join(fmt(c) for c in cellsf) + ' & ' +
                    ' & '.join(fmtpm(g, 4) for g in gaps) + r' \\')
        AUDIT.append(('5.9 correctness', cond, 'acc f1/qwen/llama',
                      [round(float(c), 4) for c in cellsf]))
    return table(
        'Generator accuracy and the discrete-semantic-entropy minus surface-entropy AUROC '
        'difference under each correctness rule, using the released-code entailment model '
        'at $T=1.0$. The same answers are graded three ways. The difference changes sign '
        'between the token-overlap rule and either LLM judge.',
        'tab:correctness', '@{}lcccccc@{}',
        r'& \multicolumn{3}{c}{Accuracy} & \multicolumn{3}{c}{SE $-$ surface} \\'
        '\n\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n'
        'Condition & token-F1 & Qwen & Llama & token-F1 & Qwen & Llama \\\\', rows)


def t_degenerate_cells():
    sub = T1[(T1.condition == 'chat_0shot') & (T1.grader == F1) &
             (T1.method == 'discrete_semantic_entropy') & (T1.entailment_backend == XL)]
    rows = []
    for _, r in sub[sub.accuracy < 0.05].sort_values('accuracy', kind='stable').iterrows():
        mdl = r.model.split('_')[-1].replace('-Instruct', '')
        rows.append(f'{r.dataset} & \\texttt{{{mdl}}} & {int(r.seed)} & '
                    f'{r.accuracy:.4f} & {int(round(r.accuracy*r.n_records))} '
                    f'/ {int(r.n_records)} \\\\')
        AUDIT.append(('5.9 degenerate', f'{r.dataset}/{mdl}/{int(r.seed)}', 'acc',
                      round(float(r.accuracy), 4)))
    return table(
        'Cells in which the token-overlap rule labels almost nothing correct '
        '(\\texttt{chat\\_0shot}, $T=1.0$). When only a few answers are correct, '
        'AUROC is highly uncertain. No LLM-graded short-answer cell in the study '
        'falls below 0.36 accuracy.',
        'tab:degenerate-cells', '@{}llccc@{}',
        'Dataset & Generator & Seed & token-F1 accuracy & Correct / records \\\\', rows)


def t_complete_t1():
    """Cover every recorded short-answer method/backend/grader group at T=1."""
    tables = []
    for cond in COND:
        rows = []
        for b in [XL, LG, QW]:
            sub = T1[(T1.condition == cond) & (T1.entailment_backend == b)]
            if sub.empty:
                continue
            rows.append(r'\multicolumn{4}{@{}l}{' + BACKEND[b] + r'} \\*')
            for m in PRETTY:
                if m not in set(sub.method):
                    continue
                vals = [unit_stat(cells(sub[(sub.method == m) & (sub.grader == g)]))
                        for g in [QJ, LJ, F1]]
                rows.append(PRETTY[m] + ' & ' + ' & '.join(fmt(v,4) for v in vals) + r' \\')
            rows.append(r'\addlinespace[4pt]')
        tables.append(table(
            f'All recorded methods for {COND[cond]} at $T=1.0$. Mean AUROC '
            'over nine dataset--generator units, each averaged over three seeds. '
            'Groups use the entailment-model labels in the export. String-based '
            'methods and P(True) do not require an entailment model. Repeated '
            'entries preserve the recorded grouping.',
            'tab:complete-' + cond.replace('_', '-'), '@{}lccc@{}',
            'Method & Qwen judge & Llama judge & token-F1 \\\\', rows))
    return '\n'.join(tables)


def t_complete_temperature():
    """Cover both valid graders, both prompts/backends, and all five methods."""
    tables = []
    methods = list(PRETTY)[:5]
    for cond in ['chat_0shot', 'default_5shot']:
        for b in [XL, QW]:
            rows = []
            for g in [QJ, LJ]:
                rows.append(r'\multicolumn{6}{@{}l}{' + GRADER[g] + r'} \\*')
                for m in methods:
                    vals = [unit_stat(cells(sa[(sa.condition == cond) &
                        (sa.entailment_backend == b) & (sa.grader == g) &
                        (sa.method == m) & (sa.temperature == t)]))
                        for t in [0.1, 0.3, 0.5, 0.7, 1.0]]
                    rows.append(PRETTY[m] + ' & ' +
                                ' & '.join(fmt(v,4) for v in vals) + r' \\')
                rows.append(r'\addlinespace[4pt]')
            tables.append(table(
                f'Complete LLM-graded temperature results for {COND[cond]}, '
                f'{BACKEND[b]}. Mean AUROC over nine dataset--generator units '
                'and three seeds per unit. The graded answers and labels stay '
                'fixed. Token-F1 sweep results are excluded as explained in '
                r'Section~\ref{sec:temperature-sweep}.',
                'tab:sweep-' + cond.replace('_', '-') + ('-default' if b == XL else '-qwen'),
                '@{}lccccc@{}', 'Method & $T=0.1$ & $0.3$ & $0.5$ & $0.7$ & $1.0$ \\\\', rows))
    return '\n'.join(tables)


def t_longform_by_generator():
    rows = []
    for model, sub in lf.groupby('model', sort=True):
        rows.append(r'\multicolumn{6}{@{}l}{' + model.split('_', 1)[-1].replace('-Instruct-v0.3','').replace('-Instruct','') + r'} \\*')
        for b in ['exact-match', 'posthoc-nli-deberta-v3-base',
                  'posthoc-nli-deberta-v3-large', 'posthoc-llm-judge-qwen2.5-72b-instruct']:
            vals = [sub[(sub.entailment_backend == b) & (sub.method == m)].auroc.mean()
                    for m in ['discrete_semantic_entropy', 'surface_entropy', 'naive_sample_entropy']]
            rows.append(LONGFORM_BACKEND[b] + ' & ' + ' & '.join(fmt(v,4) for v in vals) +
                        ' & ' + longform_intervals(model, b) + r' \\')
        rows.append(r'\addlinespace[4pt]')
    return table('Long-form biography AUROC by generator, averaged over three '
                 'seeds. This expands the nine-run averages in '
                 r'Table~\ref{tab:longform}. The final columns give discrete SE '
                 'minus each string baseline and records-only 95\\,\\% intervals '
                 'from 2,000 paired resamples within runs. The three seeds stay '
                 'fixed. These conditional intervals do not include variation '
                 'across datasets or generators.',
                 'tab:longform-by-generator', '@{}lccccc@{}', LONGFORM_HEADER, rows)


def t_answer_length():
    rows = []
    for condition in ['default_5shot', 'chat_5shot', 'default_0shot', 'chat_0shot']:
        sub = T1[(T1.condition == condition) & (T1.entailment_backend == XL) &
                 (T1.grader == QJ)]
        length = unit_stat(cells(sub[sub.method == 'discrete_semantic_entropy'],
                                 'mean_answer_chars'))
        naive = unit_stat(paired(sub, 'discrete_semantic_entropy', 'naive_entropy'))
        surface = unit_stat(paired(sub, 'discrete_semantic_entropy', 'surface_entropy'))
        rows.append(f'{COND[condition]} & {length:.1f} & {naive:+.4f} & {surface:+.4f} '
                    + r'\\')
    return table(
        'Mean graded-answer length and AUROC gains of discrete semantic entropy (SE) '
        'over naive predictive entropy and surface entropy. Qwen judge, default '
        'entailment model, $T=1.0$, with nine dataset--generator pairs and three seeds. '
        'Prompting conditions also differ in instruction and example count.',
        'tab:answer-length', '@{}lrrr@{}',
        r'Condition & Mean characters & SE $-$ naive & SE $-$ surface \\', rows)


# ---------------------------------------------------------------- seed noise floor
def t_seed_noise():
    sv = SEED_VARIABILITY
    rows = []
    for m in ['discrete_semantic_entropy', 'semantic_entropy_full', 'surface_entropy',
              'naive_entropy', 'naive_sample_entropy', 'ptrue_uncertainty']:
        s = sv[sv.method == m]
        rows.append(f'{PRETTY[m]} & {s.mean_seed_range.mean():.4f} & '
                    f'{s.max_seed_range.max():.4f} \\\\')
        AUDIT.append(('5.0 seed noise', m, 'mean range',
                      round(float(s.mean_seed_range.mean()), 4)))
    return table(
        'Variation across generation seeds. The table gives the AUROC range across the '
        'three seeds, averaged over dataset--model combinations and the recorded settings '
        'for each method. P(True) covers the two main prompting conditions at $T=1.0$. These ranges are '
        'descriptive references, not thresholds for statistical significance.',
        'tab:seed-noise', '@{}lcc@{}',
        'Method & Mean seed range & Max seed range \\\\', rows)


if __name__ == '__main__':
    from check_thesis_measurements import check_measurements, check_supporting_exports, read_rows
    measurement_rows = read_rows(DATA)
    check_measurements(measurement_rows)
    check_supporting_exports(measurement_rows)
    print('building Chapter 5 tables from', DATA)
    write('t_seed_noise.tex',        t_seed_noise())
    write('t_sentence_length.tex',   t_sentence_length())
    write('t_short_phrase.tex',      t_short_phrase())
    write('t_answer_length.tex',     t_answer_length())
    write('t_ladder.tex',           t_ladder())
    write('t_canonical_eight.tex',   t_canonical_eight())
    write('t_resampling_schemes.tex', t_resampling_schemes())
    write('t_all_slices.tex',        t_all_slices())
    write('t_paper_baselines.tex',   t_paper_baselines())
    write('t_ptrue_size.tex',        t_ptrue_size())
    write('t_backend.tex',           t_backend())
    write('t_grader_check.tex',      t_backend_grader_check())
    write('t_backend_by_model.tex', t_backend_by_model())
    write('t_factorial.tex',         t_factorial())
    write('t_temperature.tex',       t_temperature())
    write('t_correctness.tex',       t_correctness())
    write('t_degenerate_cells.tex',  t_degenerate_cells())
    write('t_complete_t1.tex',       t_complete_t1())
    write('t_complete_temperature.tex', t_complete_temperature())
    # Imported records-only intervals do not consume the shared unit-CI RNG.
    write('t_longform.tex',          t_longform())
    write('t_longform_by_generator.tex', t_longform_by_generator())
    print('\n--- audit trail ---')
    for a in AUDIT:
        print(' ', ' | '.join(str(x) for x in a))


# ---------------------------------------------------------------- figures
def method_comparison_summary(condition):
    """Per-dataset/model seed means and sample SDs for the eight recorded methods."""
    selected = []
    for method in PRETTY:
        backend = LG if method in ('accuracy_probe_uncertainty', 'probe_uncertainty') else XL
        selected.append(T1[(T1.condition == condition) &
                           (T1.entailment_backend == backend) &
                           (T1.grader == QJ) & (T1.method == method)])
    return pd.concat(selected).groupby(['dataset', 'model', 'method']).auroc.agg(
        ['mean', 'std'])


def longform_comparison_figure(outdir):
    """Plot long-form semantic entropy by entailment model and generator."""
    import matplotlib.pyplot as plt

    backends = [
        ('exact-match', 'Exact\nmatch'),
        ('posthoc-nli-deberta-v3-base', 'DeBERTa\nbase'),
        ('posthoc-nli-deberta-v3-large', 'DeBERTa\nlarge'),
        ('posthoc-llm-judge-qwen2.5-72b-instruct', 'Qwen\n72B'),
    ]
    models = [
        ('Mistral-7B', 'Mistral 7B'),
        ('Llama-3.1-8B', 'Llama 3.1 8B'),
        ('Llama-3.1-70B', 'Llama 3.1 70B'),
    ]
    fig, axes = plt.subplots(1, 3, figsize=(6.7, 2.75), sharey=True)
    for ax, (model, title) in zip(axes, models):
        dse = []
        for backend, _ in backends:
            sub = lf[(lf.model == model) & (lf.entailment_backend == backend) &
                     (lf.method == 'discrete_semantic_entropy')]
            dse.append(float(sub.auroc.mean()))
        surface = float(lf[(lf.model == model) & (lf.method == 'surface_entropy')].auroc.mean())
        naive = float(lf[(lf.model == model) & (lf.method == 'naive_sample_entropy')].auroc.mean())
        x = np.arange(len(backends))
        ax.plot(x, dse, color='#0072b2', marker='o', lw=1.5, ms=4,
                label='Discrete semantic entropy', zorder=4)
        ax.axhline(surface, color='#d55e00', lw=1.1, ls='--', label='Surface entropy')
        ax.axhline(naive, color='#7b6b8d', lw=1.1, ls=':', label='Naive sample entropy')
        ax.axhline(0.5, color='#999999', lw=0.6, zorder=1)
        ax.set_title(title, fontsize=8.5)
        ax.set_xticks(x)
        ax.set_xticklabels([label for _, label in backends], fontsize=6.4)
        ax.set_ylim(0.45, 0.78)
        ax.set_yticks([0.5, 0.6, 0.7])
        ax.grid(axis='y', color='#dddddd', lw=0.45, zorder=0)
        ax.tick_params(length=2, labelsize=6.8)
    axes[0].set_ylabel('AUROC', fontsize=8)
    # Figure-level legend above the panels: the Mistral curve reaches the top of
    # the data area, so any in-axes placement overlaps it.
    fig.legend(*axes[0].get_legend_handles_labels(), loc='upper center',
               bbox_to_anchor=(0.5, 1.0), ncol=3, fontsize=6.6, frameon=False,
               columnspacing=0.8, handlelength=1.6, handletextpad=0.5)
    fig.tight_layout(rect=(0, 0, 1, 0.88), w_pad=0.8)
    fig.savefig(os.path.join(outdir, 'longform_comparison.pdf'))
    plt.close(fig)



def figures(outdir='figures'):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    os.makedirs(outdir, exist_ok=True)
    plt.rcParams.update({'font.size': 8, 'axes.spines.top': False,
                         'axes.spines.right': False, 'figure.dpi': 200,
                         'savefig.bbox': 'tight', 'axes.linewidth': 0.6,
                         'xtick.major.width': 0.6, 'ytick.major.width': 0.6})
    longform_comparison_figure(outdir)
    INK, MUTE, HL = '#1a1a1a', '#8c8c8c', '#c1440e'
    SURF, ACCENT = '#fcfcfb', '#c1440e'

    # --- method bars by dataset and generator ----------------------------
    method_order = [
        'semantic_entropy_full', 'discrete_semantic_entropy', 'surface_entropy',
        'naive_entropy', 'naive_sample_entropy', 'ptrue_uncertainty',
        'accuracy_probe_uncertainty', 'probe_uncertainty',
    ]
    method_labels = [
        'Weighted semantic entropy', 'Discrete semantic entropy',
        'Surface entropy', 'Naive predictive entropy', 'Naive sample entropy',
        'P(True)', 'Accuracy probe', 'Semantic entropy probe',
    ]
    colors = ['#0072b2', '#56b4e9', '#d55e00', '#7b6b8d',
              '#aaaaaa', '#cc79a7', '#009e73', '#e5b732']
    # Grayscale rule: no two series may share both a near-identical grayscale
    # value and the same hatch. Luminances (Rec.709) are 94, 164, 113, 113,
    # 170, 142, 121, 183. That puts surface/naive-predictive/accuracy-probe in
    # one cluster and discrete-SE/naive-sample in another, so those are split
    # by pattern rather than by color alone.
    hatches = ['', '//', '\\\\', '', 'xx', '', '..', '//']
    datasets = [('triviaqa', 'TriviaQA'), ('nqopen', 'NQ-Open'), ('svamp', 'SVAMP')]
    models = ['mistralai_Mistral-7B-Instruct-v0.3',
              'meta-llama_Llama-3.1-8B-Instruct',
              'meta-llama_Llama-3.1-70B-Instruct']
    for condition, filename in [('chat_0shot', 'method_comparison'),
                                ('default_5shot', 'method_comparison_short')]:
        summary = method_comparison_summary(condition)
        fig, axes = plt.subplots(1, 3, figsize=(6.8, 3.35), sharey=True)
        width = 0.1
        for ax, (dataset, title) in zip(axes, datasets):
            for j, method in enumerate(method_order):
                rows = summary.loc[[(dataset, model, method) for model in models]]
                x = np.arange(3) + (j - 3.5) * width
                ax.bar(x, rows['mean'], width * 0.94, yerr=rows['std'],
                       color=colors[j], hatch=hatches[j], edgecolor='white',
                       linewidth=0.25, capsize=1.2, zorder=3,
                       error_kw={'elinewidth': 0.55, 'capthick': 0.55},
                       label=method_labels[j] if dataset == 'triviaqa' else None)
            ax.axhline(0.5, color=MUTE, lw=0.7, ls=':', zorder=2)
            ax.set_title(title, fontsize=9)
            ax.set_xticks(range(3))
            ax.set_xticklabels(['Mistral\n7B', 'Llama 3.1\n8B', 'Llama 3.1\n70B'],
                               fontsize=7)
            ax.set_ylim(0, 1)
            ax.set_yticks([0, 0.25, 0.5, 0.75, 1])
            ax.grid(axis='y', color='#dddddd', lw=0.45, zorder=0)
            ax.tick_params(length=2, labelsize=7)
        axes[0].set_ylabel('AUROC', fontsize=8)
        fig.legend(loc='upper center', bbox_to_anchor=(0.5, 1.0),
                   ncol=4, fontsize=7.1, frameon=False, columnspacing=0.8,
                   handlelength=1.6, handletextpad=0.5)
        fig.tight_layout(rect=(0, 0, 1, 0.80), w_pad=1.0)
        fig.savefig(f'{outdir}/{filename}.pdf')
        plt.close(fig)
        print(f'  wrote {outdir}/{filename}.pdf')

    # --- temperature ------------------------------------------------------
    fig, ax = plt.subplots(figsize=(4.4, 2.9))
    styles = {'discrete_semantic_entropy': ('-', 'o', INK),
              'surface_entropy': ('--', 's', MUTE),
              'naive_entropy': (':', '^', HL)}
    Ts = [0.1, 0.3, 0.5, 0.7, 1.0]
    for m, (ls, mk, c) in styles.items():
        ys = []
        for t in Ts:
            sub = sa[(sa.condition == 'chat_0shot') & (sa.entailment_backend == XL) &
                     (sa.grader == QJ) & (sa.temperature == t) & (sa.method == m)]
            ys.append(unit_stat(cells(sub)))
        ax.plot(Ts, ys, ls, marker=mk, ms=3.4, lw=1.2, color=c, label=PRETTY[m])
    ax.axhline(0.5, color=MUTE, lw=0.6, ls='-', alpha=0.5)
    ax.text(0.105, 0.505, 'chance', fontsize=6, color=MUTE, va='bottom')
    ax.set_xlabel('sampling temperature'); ax.set_ylabel('AUROC')
    ax.set_xticks(Ts); ax.legend(frameon=False, fontsize=6.8, loc='lower right')
    ax.tick_params(length=2)
    fig.savefig(f'{outdir}/temperature.pdf'); plt.close(fig)
    print(f'  wrote {outdir}/temperature.pdf')

    # --- entailment-model comparison for the main short-answer experiment --
    fig, ax = plt.subplots(figsize=(4.4, 2.9))
    bs = [LG, XL, QW]
    ys = [unit_stat(cells(T1[(T1.condition == 'chat_0shot') & (T1.entailment_backend == b) &
                             (T1.grader == QJ) & (T1.method == 'discrete_semantic_entropy')]))
          for b in bs]
    srf = unit_stat(cells(T1[(T1.condition == 'chat_0shot') & (T1.entailment_backend == XL) &
                             (T1.grader == QJ) & (T1.method == 'surface_entropy')]))
    ax.plot(range(3), ys, '-o', ms=4, lw=1.2, color=INK)
    ax.axhline(srf, color=HL, lw=1.0, ls='--')
    ax.text(-0.28, srf, 'surface entropy', fontsize=6.2, color=HL,
            va='bottom', ha='left')
    ax.set_xticks(range(3)); ax.set_xticklabels(['v3-large', 'xlarge\n(default)', 'Qwen-72B'],
                                                fontsize=6.6)
    ax.set_ylabel('AUROC'); ax.set_title('sentence-length answers', fontsize=7.4)
    ax.set_xlim(-0.35, 2.75); ax.tick_params(length=2)
    fig.savefig(f'{outdir}/backend_ladder.pdf'); plt.close(fig)
    print(f'  wrote {outdir}/backend_ladder.pdf')

    # ---- ladder ----
    NOISE=SEED_REFERENCE
    # ---------------- Figure 1: the four-rung decomposition ----------------
    rungs=[('naive_sample_entropy','naive_entropy','count strings,\nnot likelihoods'),
           ('surface_entropy','naive_sample_entropy','normalize before\ncounting'),
           ('discrete_semantic_entropy','surface_entropy','cluster by\nmeaning'),
           ('semantic_entropy_full','discrete_semantic_entropy','weight clusters\nby likelihood')]
    rows=[]
    for hi,lo,lab in rungs:
        mus=[];rf=0;ra=0
        for (c,b,g),sub in T1.groupby(['condition','entailment_backend','grader']):
            diff=paired(sub,hi,lo)
            if len(diff)<9: continue
            mu,l,h=unit_ci(diff); mus.append(mu); rf+=int(l>0); ra+=int(h<0)
        mus=np.array(mus)
        rows.append(dict(lab=lab,mean=mus.mean(),pos=int((mus>0).sum()),n=len(mus),rf=rf,ra=ra))
    R=pd.DataFrame(rows)

    fig,ax=plt.subplots(figsize=(4.8,2.3))
    y=np.arange(len(R))[::-1]
    for i,(yy,r) in enumerate(zip(y,R.itertuples())):
        hot = r.lab.startswith('normalize')
        ax.barh(yy, r.mean, height=0.52, color=ACCENT if hot else INK,
                edgecolor=SURF, linewidth=1.0, zorder=3)
        ax.text(r.mean+0.0012, yy, f'{r.mean:+.4f}', va='center', ha='left',
                fontsize=9, color=ACCENT if hot else INK,
                fontweight='bold' if hot else 'normal', zorder=4)
    ax.axvline(NOISE, color=MUTE, lw=0.9, ls=(0,(4,2)), zorder=2)
    ax.annotate('mean seed range', xy=(NOISE, len(R)-0.45), xytext=(NOISE, len(R)-0.15),
                fontsize=9, color=INK, ha='center', va='bottom', annotation_clip=False)
    ax.axvline(0, color=INK, lw=0.7, zorder=2)
    ax.set_yticks(y); ax.set_yticklabels(R.lab, fontsize=9)
    ax.set_xlim(-0.004, 0.048)
    ax.set_xticks([0,0.01,0.02,0.03,0.04])
    ax.set_xlabel('mean AUROC change, 24 configuration entries', fontsize=9)
    ax.tick_params(length=2, labelsize=9); ax.spines['left'].set_visible(False)
    fig.savefig(f'{outdir}/ladder.pdf'); plt.close(fig)
    print(f'  wrote {outdir}/ladder.pdf')


if __name__ == '__main__':
    figures(os.path.join(os.path.dirname(OUT) or '.', 'figures'))
